feat(collect-subscribers): add option to inject klaviyo form capturin…
YotpoLtd/magento2-module-messaging pull request #127
Opened 2023-06-02 09:48 UTC by zzlatev-yotpo

…g script

<img width="1014" alt="image" src="https://github.com/YotpoLtd/magento2-module-messaging/assets/113969802/f321193a-d1e8-431f-8af9-fa259c227ffe">

2023-06-02 13:16 UTC, gserbezov approved these changes

2023-07-05 20:33 UTC, LiorGingi requested changes

2023-07-05 20:33 UTC, LiorGingi commented on etc/config.xml
> +                    <capture_klaviyo_forms>1</capture_klaviyo_forms>
Should be 0 by default.

2023-07-05 20:33 UTC, LiorGingi commented on view/frontend/templates/klaviyo_subscription_integration.phtml
> +    require(['https://d18eg7dreypte5.cloudfront.net/scripts/integrations/subscription.js'])
Any reason why not doing this through requirejs-config and injection?

2023-07-17 07:47 UTC, LiorGingi approved these changes

2023-07-17 07:50 UTC, LiorGingi approved these changes

2023-07-17 07:50 UTC, merged